In [272]:
import random as rnd

x = rnd.randint(0,100)

print(x)

41


In [274]:
import numpy as np

vettore = np.array([1, 5, 3, 4, 2])
print(vettore)
print(type(vettore))

[1 5 3 4 2]
<class 'numpy.ndarray'>


In [286]:
matrice = np.array([[0, 1, 0, 0, 0],
                   [0, 0, 1, 0, 1], 
                   [1, 0, 0, 0, 0],
                   [0, 0, 1, 0, 0],
                   [0, 1, 1, 1, 0]])

print(matrice)
print(type(matrice))

[[0 1 0 0 0]
 [0 0 1 0 1]
 [1 0 0 0 0]
 [0 0 1 0 0]
 [0 1 1 1 0]]
<class 'numpy.ndarray'>


In [367]:
v = np.array([1,5,4,3,2])
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print(f"Size v = {v.size}\n")

print(f"Shape v = {v.shape}\n")

print(f"Max v = {np.max(v)}")
print(f"Min v = {np.min(v)}")
print(f"Max v = {np.mean(v)}")
print(f"Max v = {np.std(v)}\n")

print(f"Transpose a = {np.transpose(a)}")
print(f"Transpose b = {np.transpose(b)}\n")

print(f"Ordered v = {np.sort(v)}\n")

print(f"Sum a + b = {a + b}")
print(f"Difference a - b = {a - b}\n")

print(f"Multiplication a * b = {np.dot(a, b)}\n")

vec = np.arange(0, 10)
print(f"Vettore da 0 - 9: {vec}\n")

vec4 = np.arange(4, 37, 4)
print(f"Vettore da 4 a 36 con solo multipli di 4: {vec4}\n")

mat0 = np.zeros((2, 2), dtype=np.int8)
print(f"Matrice 2 x 2 di soli zero: {mat0}\n")

mat1 = np.ones((2, 2), dtype=np.int8)
print(f"Matrice 2 x 2 di soli uno: {mat1}\n")

mat3 = np.full((10, 10), 3)
print(f"Matrice 10 x 10 di soli 3: {mat3}\n")

mat17 = np.ones((10, 10))
np.fill_diagonal(mat17, 7)
print(f"Matrice 10 x 10 piena di 1 con 7 nelle diagonali: {mat17}\n")

mat17[mat17 == 7] = 9
print(f"Matrice 10 x 10 piena di 1 e 9 nelle diagonali: {mat17}")

Size v = 5

Shape v = (5,)

Max v = 5
Min v = 1
Max v = 3.0
Max v = 1.4142135623730951

Transpose a = [[1 3]
 [2 4]]
Transpose b = [[5 7]
 [6 8]]

Ordered v = [1 2 3 4 5]

Sum a + b = [[ 6  8]
 [10 12]]
Difference a - b = [[-4 -4]
 [-4 -4]]

Multiplication a * b = [[19 22]
 [43 50]]

Vettore da 0 - 9: [0 1 2 3 4 5 6 7 8 9]

Vettore da 4 a 36 con solo multipli di 4: [ 4  8 12 16 20 24 28 32 36]

Matrice 2 x 2 di soli zero: [[0 0]
 [0 0]]

Matrice 2 x 2 di soli uno: [[1 1]
 [1 1]]

Matrice 10 x 10 di soli 3: [[3 3 3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3 3 3]]

Matrice 10 x 10 piena di 1 con 7 nelle diagonali: [[7. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 7. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 7. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 7. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 7. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 7. 1. 1. 1. 1.]
 [1. 1. 